services:
  fastgpt-dify-adapter:
    container_name: fastgpt-dify-adapter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    image: hotwa/fastgpt-dify-adapter:1.0.0
    env_file:
      - .env
    restart: unless-stopped
